name: Backend CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t your-username/your-backend:latest .
          docker push your-username/your-backend:latest

      - name: Deploy to Server
        run: |
          ssh user@your-server "docker pull your-username/your-backend:latest && docker-compose -f /path/to/docker-compose.yml up -d"
